//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 01:16:31 AM BRT 
//


package gerenciadorPagamentosJaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for boletoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boletoVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataDeProcessamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="instrucao1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucao8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrucaoAoSacado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="localPagamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="textosExtras">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="titulo" type="{}tituloVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boletoVO", propOrder = {
    "dataDeProcessamento",
    "instrucao1",
    "instrucao2",
    "instrucao3",
    "instrucao4",
    "instrucao5",
    "instrucao6",
    "instrucao7",
    "instrucao8",
    "instrucaoAoSacado",
    "localPagamento",
    "textosExtras",
    "titulo"
})
public class BoletoVO {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataDeProcessamento;
    protected String instrucao1;
    protected String instrucao2;
    protected String instrucao3;
    protected String instrucao4;
    protected String instrucao5;
    protected String instrucao6;
    protected String instrucao7;
    protected String instrucao8;
    protected String instrucaoAoSacado;
    protected String localPagamento;
    @XmlElement(required = true)
    protected BoletoVO.TextosExtras textosExtras;
    protected TituloVO titulo;

    /**
     * Gets the value of the dataDeProcessamento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataDeProcessamento() {
        return dataDeProcessamento;
    }

    /**
     * Sets the value of the dataDeProcessamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataDeProcessamento(XMLGregorianCalendar value) {
        this.dataDeProcessamento = value;
    }

    /**
     * Gets the value of the instrucao1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao1() {
        return instrucao1;
    }

    /**
     * Sets the value of the instrucao1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao1(String value) {
        this.instrucao1 = value;
    }

    /**
     * Gets the value of the instrucao2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao2() {
        return instrucao2;
    }

    /**
     * Sets the value of the instrucao2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao2(String value) {
        this.instrucao2 = value;
    }

    /**
     * Gets the value of the instrucao3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao3() {
        return instrucao3;
    }

    /**
     * Sets the value of the instrucao3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao3(String value) {
        this.instrucao3 = value;
    }

    /**
     * Gets the value of the instrucao4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao4() {
        return instrucao4;
    }

    /**
     * Sets the value of the instrucao4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao4(String value) {
        this.instrucao4 = value;
    }

    /**
     * Gets the value of the instrucao5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao5() {
        return instrucao5;
    }

    /**
     * Sets the value of the instrucao5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao5(String value) {
        this.instrucao5 = value;
    }

    /**
     * Gets the value of the instrucao6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao6() {
        return instrucao6;
    }

    /**
     * Sets the value of the instrucao6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao6(String value) {
        this.instrucao6 = value;
    }

    /**
     * Gets the value of the instrucao7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao7() {
        return instrucao7;
    }

    /**
     * Sets the value of the instrucao7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao7(String value) {
        this.instrucao7 = value;
    }

    /**
     * Gets the value of the instrucao8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucao8() {
        return instrucao8;
    }

    /**
     * Sets the value of the instrucao8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucao8(String value) {
        this.instrucao8 = value;
    }

    /**
     * Gets the value of the instrucaoAoSacado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucaoAoSacado() {
        return instrucaoAoSacado;
    }

    /**
     * Sets the value of the instrucaoAoSacado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucaoAoSacado(String value) {
        this.instrucaoAoSacado = value;
    }

    /**
     * Gets the value of the localPagamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalPagamento() {
        return localPagamento;
    }

    /**
     * Sets the value of the localPagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalPagamento(String value) {
        this.localPagamento = value;
    }

    /**
     * Gets the value of the textosExtras property.
     * 
     * @return
     *     possible object is
     *     {@link BoletoVO.TextosExtras }
     *     
     */
    public BoletoVO.TextosExtras getTextosExtras() {
        return textosExtras;
    }

    /**
     * Sets the value of the textosExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoletoVO.TextosExtras }
     *     
     */
    public void setTextosExtras(BoletoVO.TextosExtras value) {
        this.textosExtras = value;
    }

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link TituloVO }
     *     
     */
    public TituloVO getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloVO }
     *     
     */
    public void setTitulo(TituloVO value) {
        this.titulo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class TextosExtras {

        protected List<BoletoVO.TextosExtras.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BoletoVO.TextosExtras.Entry }
         * 
         * 
         */
        public List<BoletoVO.TextosExtras.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<BoletoVO.TextosExtras.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected String key;
            protected String value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
