//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 01:16:31 AM BRT 
//


package gerenciadorPagamentosJaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contaBancariaVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contaBancariaVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="agencia" type="{}agenciaVO" minOccurs="0"/>
 *         &lt;element name="carteira" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codigoDeCompensacaoBACEN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="digitoDaConta" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="numeroDaConta" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contaBancariaVO", propOrder = {
    "agencia",
    "carteira",
    "codigoDeCompensacaoBACEN",
    "digitoDaConta",
    "numeroDaConta"
})
public class ContaBancariaVO {

    protected AgenciaVO agencia;
    protected Integer carteira;
    protected String codigoDeCompensacaoBACEN;
    protected Integer digitoDaConta;
    protected Integer numeroDaConta;

    /**
     * Gets the value of the agencia property.
     * 
     * @return
     *     possible object is
     *     {@link AgenciaVO }
     *     
     */
    public AgenciaVO getAgencia() {
        return agencia;
    }

    /**
     * Sets the value of the agencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgenciaVO }
     *     
     */
    public void setAgencia(AgenciaVO value) {
        this.agencia = value;
    }

    /**
     * Gets the value of the carteira property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCarteira() {
        return carteira;
    }

    /**
     * Sets the value of the carteira property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCarteira(Integer value) {
        this.carteira = value;
    }

    /**
     * Gets the value of the codigoDeCompensacaoBACEN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDeCompensacaoBACEN() {
        return codigoDeCompensacaoBACEN;
    }

    /**
     * Sets the value of the codigoDeCompensacaoBACEN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDeCompensacaoBACEN(String value) {
        this.codigoDeCompensacaoBACEN = value;
    }

    /**
     * Gets the value of the digitoDaConta property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDigitoDaConta() {
        return digitoDaConta;
    }

    /**
     * Sets the value of the digitoDaConta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDigitoDaConta(Integer value) {
        this.digitoDaConta = value;
    }

    /**
     * Gets the value of the numeroDaConta property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroDaConta() {
        return numeroDaConta;
    }

    /**
     * Sets the value of the numeroDaConta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroDaConta(Integer value) {
        this.numeroDaConta = value;
    }

}
