//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 01:16:31 AM BRT 
//


package gerenciadorPagamentosJaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gerenciadorPagamentosJaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gerenciadorPagamentosJaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BoletoVO }
     * 
     */
    public BoletoVO createBoletoVO() {
        return new BoletoVO();
    }

    /**
     * Create an instance of {@link BoletoVO.TextosExtras }
     * 
     */
    public BoletoVO.TextosExtras createBoletoVOTextosExtras() {
        return new BoletoVO.TextosExtras();
    }

    /**
     * Create an instance of {@link TituloVO }
     * 
     */
    public TituloVO createTituloVO() {
        return new TituloVO();
    }

    /**
     * Create an instance of {@link ContaBancariaVO }
     * 
     */
    public ContaBancariaVO createContaBancariaVO() {
        return new ContaBancariaVO();
    }

    /**
     * Create an instance of {@link AgenciaVO }
     * 
     */
    public AgenciaVO createAgenciaVO() {
        return new AgenciaVO();
    }

    /**
     * Create an instance of {@link EnderecoVO }
     * 
     */
    public EnderecoVO createEnderecoVO() {
        return new EnderecoVO();
    }

    /**
     * Create an instance of {@link PessoaVO }
     * 
     */
    public PessoaVO createPessoaVO() {
        return new PessoaVO();
    }

    /**
     * Create an instance of {@link BoletoVO.TextosExtras.Entry }
     * 
     */
    public BoletoVO.TextosExtras.Entry createBoletoVOTextosExtrasEntry() {
        return new BoletoVO.TextosExtras.Entry();
    }

}
